[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/api/ai"
  to = "/.netlify/functions/ai"
  status = 200
